# Generated by Django 5.0 on 2023-12-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('company', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('user_id', models.BigIntegerField(unique=True)),
                ('credit', models.FloatField()),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'info',
                'managed': True,
            },
        ),
    ]
