# Generated by Django 5.0 on 2023-12-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userinfo_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': True, 'verbose_name': 'User Info', 'verbose_name_plural': 'Users Info'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.CharField(max_length=250),
        ),
    ]
